# Generated by Django 4.2.6 on 2024-02-18 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('date_and_time_of_payment', models.DateTimeField(auto_now_add=True)),
                ('turn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.turn')),
            ],
        ),
    ]
