# Generated by Django 5.0.2 on 2024-02-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nick_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
