# Generated by Django 5.0.2 on 2024-02-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_rename_estado_actual_historaldecitas_estado_actual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profesional",
            name="role",
            field=models.CharField(
                choices=[("profesional", "Profesional"), ("usuario", "Usuario")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="role",
            field=models.CharField(
                choices=[("profesional", "Profesional"), ("usuario", "Usuario")],
                default="",
                max_length=20,
            ),
        ),
    ]
