# Generated by Django 5.0.2 on 2024-02-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_professional_user_remove_turno_id_disponibilidad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availability",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Lunes", "Lunes"),
                    ("Martes", "Martes"),
                    ("Miercoles", "Miercoles"),
                    ("Jueves", "Jueves"),
                    ("Viernes", "Viernes"),
                    ("Sabado", "Sabado"),
                    ("Domingo", "Domingo"),
                ],
                max_length=10,
            ),
        ),
    ]
