# Generated by Django 5.0.2 on 2024-02-13 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_availability_day_of_week"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Messages",
            new_name="Message",
        ),
    ]
