# Generated by Django 4.2.3 on 2024-02-28 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nick_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('professional', 'Professional'), ('user', 'User')], default='user', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('rating_date', models.DateTimeField(auto_now_add=True)),
                ('turn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.turn')),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('professional_id', models.AutoField(primary_key=True, serialize=False)),
                ('speciality', models.CharField(default='Contador', max_length=100)),
                ('description', models.TextField(default='Profesional de confianza', max_length=100)),
                ('availability_hours', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('professional', 'Professional'), ('user', 'User')], default='professional', max_length=20)),
                ('neighborhood', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(blank=True, default='Buenos Aires', max_length=100)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_content', models.TextField()),
                ('date_and_time_of_message', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('turn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.turn')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(max_length=20)),
                ('current_status', models.CharField(max_length=20)),
                ('date_and_time_of_status_change', models.DateTimeField(auto_now_add=True)),
                ('turn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.turn')),
            ],
        ),
    ]
