# Generated by Django 4.2.6 on 2024-03-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
