# Generated by Django 4.2.6 on 2024-02-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_payment_turn_id_remove_turn_availability_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='Argentina', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='province',
            field=models.CharField(default='', max_length=255),
        ),
    ]
