# Generated by Django 5.0.2 on 2024-02-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_city_customuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(choices=[(1, '6'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
