# Generated by Django 5.0.2 on 2024-03-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=10)),
                ('hour', models.TimeField()),
                ('status', models.BooleanField(default=True)),
                ('cupo', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=4200.0, max_digits=10)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('turn_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_and_time_of_turn', models.DateTimeField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('turn_status', models.CharField(choices=[('confirmed', 'Confirmado'), ('pending', 'Pendiente'), ('cancelled', 'Cancelado'), ('completed', 'Completado')], help_text='Estado del turno: Confirmado, Pendiente, Cancelado o Completado', max_length=20)),
                ('message_to_professional', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
