# Generated by Django 4.2.3 on 2024-02-28 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('turn_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_and_time_of_turn', models.DateTimeField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('turn_status', models.CharField(choices=[('confirmed', 'Confirmado'), ('pending', 'Pendiente'), ('cancelled', 'Cancelado'), ('completed', 'Completado')], help_text='Estado del turno: Confirmado, Pendiente, Cancelado o Completado', max_length=20)),
                ('message_to_professional', models.TextField(blank=True, null=True)),
                ('availability_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appointments.availability')),
            ],
        ),
    ]
