# Generated by Django 5.0.2 on 2024-02-22 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='professional_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professional'),
        ),
        migrations.AddField(
            model_name='turn',
            name='availability_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appointments.availability'),
        ),
        migrations.AddField(
            model_name='turn',
            name='professional_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professional'),
        ),
        migrations.AddField(
            model_name='turn',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
