# Generated by Django 4.2.3 on 2024-02-28 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='professional_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professional'),
        ),
        migrations.AddField(
            model_name='turn',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availability',
            name='professional_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professional'),
        ),
    ]
