# Generated by Django 5.0.2 on 2024-03-04 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='date_and_time_of_turn',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='turn',
            old_name='end_time',
            new_name='horario',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='id',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='start_time',
        ),
        migrations.AddField(
            model_name='turn',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turn',
            name='availability_id',
            field=models.ForeignKey(default='availability', on_delete=django.db.models.deletion.CASCADE, to='appointments.availability'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='professional_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to='users.professional'),
        ),
    ]
