# Generated by Django 4.2.6 on 2024-02-22 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='date_and_time_of_turn',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='start_time',
        ),
        migrations.AddField(
            model_name='availability',
            name='max_users',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad máxima de usuarios permitidos para esta disponibilidad'),
        ),
        migrations.AddField(
            model_name='availability',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1500, help_text='Precio de la clase', max_digits=10),
        ),
        migrations.AddField(
            model_name='availability',
            name='users',
            field=models.ManyToManyField(through='appointments.Turn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day_of_week',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='turn',
            name='turn_status',
            field=models.CharField(choices=[('confirmed', 'Confirmado'), ('pending', 'Pendiente'), ('cancelled', 'Cancelado'), ('completed', 'Completado')], default='pending', help_text='Estado del turno: Confirmado, Pendiente, Cancelado o Completado', max_length=20),
        ),
    ]
