# Generated by Django 4.2.6 on 2024-02-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_turn_date_and_time_of_turn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1500, help_text='Precio del turno', max_digits=10),
        ),
    ]
