# Generated by Django 5.0.2 on 2024-03-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_date_and_time_of_turn_turn_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='day_of_week',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
