# Generated by Django 4.2.6 on 2024-02-23 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('appointments', '0004_turn_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='availability_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='appointments.availability'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='professional_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='users.professional'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to=settings.AUTH_USER_MODEL),
        ),
    ]
