# Generated by Django 5.0.2 on 2024-03-04 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_turn_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='category',
            field=models.CharField(default='gym', max_length=100),
        ),
        migrations.AddField(
            model_name='turn',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='turn',
            name='availability_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='appointments.availability'),
        ),
    ]
